<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
* Convert date format.
*/
$listingDateFormat = $this->helper('Apptha\Airhotels\Helper\Dateformat')->getListingDateformat();
$convertedDateFormat = $this->helper('Apptha\Airhotels\Helper\Dateformat')->getConvertedDate($listingDateFormat);
?>
<?php /** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem();
$orderItem = $_item->getOrderItem();
$orderId = $this->getRequest()->getParam('order_id')?$this->getRequest()->getParam('order_id'):$orderItem->getOrderId();
$getOrderInfo = $this->helper('\Apptha\Airhotels\Helper\Order')->getOrderInformation($orderId,$_item->getProductId())->getData();
?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" colspan="5" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <div class="product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?>
        <ul>
          <li><span class="product-item-label"><?php echo __('Check In :');?></span><span class="product-item-date"><?php echo date($convertedDateFormat,strtotime($getOrderInfo[0]['fromdate']));?></span></li>
          <li><span class="product-item-label"><?php echo __('Check Out :');?></span><span class="product-item-date"><?php echo date($convertedDateFormat,strtotime($getOrderInfo[0]['todate']));?></span></li>
        </ul>
        </div>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="tooltip content">
                        <dl class="item options">
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
