<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$productId = $this->getRequest()->getParam('id');
$product = $this->helper('Apptha\Airhotels\Helper\General')->getProductData($productId);
$avg_rating = $this->helper('Apptha\Airhotels\Helper\Product')->getRatingSummary($product);
$reviewCollection = $this->getReviewPagination ($productId);
?>
     <div class="review-heading-section clearfix">
          <h4><?php echo __('Reviews');?></h4>
          <div class="rating-box" id="mainreviews">
               <div class="rating" style="width: <?php echo $avg_rating;?>%;"></div>
          </div>
     </div>
     <?php 
     if(count($reviewCollection) > 0){
          foreach($reviewCollection->getData() as $reviewValues){?>
          <div class="review-list">
               <div class="guest-image-section clearfix">
                    <div class="guest-image">
                    <?php 
                    $hostImageUrl = $this->getHostImageUrl ();
                    if($reviewValues['customer_id']){
                        $customerData = $this->getHostData ( $reviewValues['customer_id'] );                        
                         $reviewCustomerImageUrl = ($customerData->getProfileimage())? $hostImageUrl . $customerData->getProfileimage() : $block->getViewFileUrl('Apptha_Airhotels::images/no_user.jpg');
                    }else{
                         $reviewCustomerImageUrl = $block->getViewFileUrl('Apptha_Airhotels::images/no_user.jpg');
                    }
                    ?>
                         <img src="<?php echo $reviewCustomerImageUrl;?>" alt="profile">
                    </div>
                    <div class="gust-img-info">
                         <h5><?php echo $reviewValues['nickname'];?></h5>
                         <h6><?php echo date("F Y", strtotime($reviewValues["created_at"])); ?></h6>
                         <p><?php echo $reviewValues['detail'];?></p>
                    </div>
               </div>
          </div>
          <?php
           } 
     }else{ ?>     
       <span class='no_reviews'><?php echo __('Yet no reviews available.') ?></span>
    <?php }?>  
     
     <?php 
     if ($block->getPagerHtml()): ?>
         <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
     <?php endif ?>

