<?php
/**
* Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Airhotels
* @version     1.3
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2018 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/
?>

<div class="mobile-sidemenu">
<ul class="mobile-sidemenu-list">
<li><a href="<?php echo $this->getUrl('about-us');  ?> "> About us <svg class="ic-user"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#user'); ?>'></svg></a></li>
<li><a href="<?php echo $this->getUrl('terms');  ?>"> Terms <svg class="ic-login"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#form'); ?>'></svg> </a></li>
<li><a href="<?php echo $this->getUrl('privacy'); ?>"> Privacy <svg class="ic-login"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#unlock'); ?>'></svg></a></li>
<li><a href="<?php echo $this->getUrl('help'); ?>"> Help <svg class="ic-login"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#question'); ?>'></svg></a></li>
<li><a href="<?php echo $this->getUrl('why-host'); ?>"> Why Host <svg class="ic-login"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#database'); ?>'></svg></a></li>
</ul>
</div>