<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="col-left sidebar"><div class="content-block"><h2 class="account-heading"><?php echo __('My Listings')?></h2>
<div class="account-heading-contents">
  <ul>
    <li><a href="<?php echo $this->getManageListingUrl();?>"><?php echo __('Manage Listings')?></a></li>
    <li><a href="<?php echo $this->getPropertyHistoryUrl();?>" class="selected"><?php echo __('Booking History')?></a></li>
  </ul>
</div></div></div>