<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php

$delete = $this->getRequest ()->getParam ( 'multi' );
$entityIds = $this->getRequest ()->getParam ( 'id' );
$multisubmit = $this->getRequest ()->getParam ( 'multi_submit' );
$productDeleteOption = $block->getProductDeleteApproval ();
$productBulkOption = $block->getProductBulkApproval ();

?>
<?php /**
 * displaying all listings for a particular host
 */?>
<div id="rooms">
         <div id="room" class="clearfix">
  <div id="left_column">
           <div id="main_content" class="box">
    <div class="my-account">
             <h2 class="account-heading"><?php echo __('Manage Listing');?></h2>
             <div id="newlist" class="clearfix">
        <?php
        $listingUrl = '';
        ?>
            <input type="button" class="import_button"
               id="list" name="list"
               value="<?php echo __('Post new listing'); ?>"
               onClick="location.href='<?php echo $block->getUrl('airhotels/listing/form'); ?>'" />
             </div>
             <!-- Property List Start-->
             <div id="list_div" class="listing-detail" >
      <div class="fieldset" id="manage_list">
               <div class="manage-listing-content"><?php
    $model = $this->product;
    $todayDate = strtotime ( $block->currentDate () );
    $todayDate = date ( 'm/d/y', $todayDate );
    $products = $this->getCollection ();
    if (count ( $products ) != 0) {
        $c = $imageUrlStatusForProperty = 0;
        $preImageUrl = $currentImageUrl = '';
        foreach ( $products as $product ) {
            $listingUrl = $product->getProductUrl();
            /**
             * For catalog flat enabled
             */
            $product = $model->load ( $product->getId () );
            $currentImageUrl = $product->getImage ();
            if ($preImageUrl == $currentImageUrl && $preImageUrl != '') {
$imageUrlStatusForProperty = 1;
            } else {
$imageUrlStatusForProperty = 0;
            }
            $preImageUrl = $product->getImage ();
            $baseurl = $block->getMediaImageUrl ();
            $imagehelper = $this->helper ( 'Magento\Catalog\Helper\Image' );
            $yourlist= $this->helper ( 'Apptha\Airhotels\Helper\Data' )->getProductMediaUrl(). 'catalog/product/' .  $preImageUrl;
            ?>
        <div class="listing_main">
 <div class="listing-image">
            <?php if($product->getStatus() == 1) { ?>
<a
   href="<?php echo $product->getProductUrl(); ?>"
   target="_blank"
   title="<?php echo __('Click To Preview'); ?>">
            <?php } ?>
<?php if ($product->getImage()) { ?> <img
   src="<?php echo $yourlist; ?>"
   > <?php } else { ?>
    <img src=""
   > <?php } ?>
    </a>
          <div class="listing-info">
   <div class="clearfix">
            <div class="listing_user_name">
     <h5 class="manage_lisitng_title"><?php if($product->getPropertyApproved() != 0 && $product->getStatus() == 1){ ?>
<a href="<?php echo $listingUrl; ?>" target="_blank"
       title="<?php echo __('Click To Preview'); ?>">
<?php echo $product->getName(); ?></a>
<?php } else {?>
<?php echo $product->getName(); ?>
<?php }?></h5>
            </div>
            <div class="slider-widget-container">
     <ul>
              <li id="active<?php echo $c; ?>"
       <?php echo ($product->getStatus() == 2) ? "style='display:block'" : "style='display:none'"; ?>><a
       title="<?php echo __('Click to Active'); ?>"
       class="hide_grid" id="active" name="active"
      <?php if($product->getPropertyApproved() != 0) { ?> onClick="airhotelsActivate('1','<?php echo $c; ?>','hide<?php echo $c; ?>')" <?php }?> ><span
><?php echo __("HIDDEN"); ?></span></a></li>
              <li id="hide<?php echo $c; ?>"
       <?php echo ($product->getStatus() == 1 ) ? "style='display:block'" : "style='display:none'"; ?>><a
       title="<?php echo __('Click to Hide') ?>"
       class="visible_grid" id="deactive" name="active"
       onClick="airhotelsActivate('2','<?php echo $c; ?>','active<?php echo $c; ?>')"><span
><?php echo __("ACTIVE"); ?></span></a>
       <input type="hidden" id="productId<?php echo $c; ?>"
       value="<?php echo $product->getId(); ?>" /></li>
              <li id="loadingSpace<?php echo $c; ?>"
       ></li>
     </ul>
            </div>
   </div>
   <ul class="actions_grid">

            <li class="action_button"> <a class="icon_list"
     target="_blank" title="<?php echo __('Schedule') ?>"
     onClick="location.href='<?php echo $block->getUrl('airhotels/listing/blockcalendar/'); ?>id/<?php echo $product->getId(); ?>'">
              <i class="airhotel-sprite calendar list_option_icon"></i><span
              class="manage_list_options"><?php echo __('Schedule') ?></span>
            </a>
            </li> <li class="action_button"> <a
     class="icon_list" target="_blank"
     title="<?php echo __('Photos') ?>"
     onClick="location.href='<?php echo $block->getUrl('airhotels/listing/photos/'); ?>id/<?php echo $product->getId(); ?>'">
              <i class="airhotel-sprite film list_option_icon"></i><span
              class="manage_list_options"><?php echo __('Photos') ?></span>
            </a>
            </li> <li class="action_button"> <a
     class="icon_list" title="<?php echo __('Edit') ?>"
     target="_blank"
     onClick="location.href='<?php echo $block->getUrl('airhotels/listing/edit/'); ?>id/<?php echo $product->getId(); ?>'">
              <i class="airhotel-sprite edit list_option_icon"></i><span
              class="manage_list_options"><?php echo __('Edit') ?></span>
            </a>
            </li> <li class="action_button"> <a
     class="icon_list" title="<?php echo __('Delete') ?>"
     onclick="return confirm('<?php echo __('Are you sure want to delete').'?'; ?>')"
     href="<?php echo $block->getUrl('airhotels/listing/delete/'); ?>id/<?php echo $product->getId(); ?>">
              <i class="airhotel-sprite close list_option_icon"></i><span
              class="manage_list_options"><?php echo __('Delete') ?></span>
            </a>
            </li>
   </ul>
              <?php  if($product->getImage()=='') {         ?>
<span class="property-error"
            ><?php echo __("Your property will not display in front end until images uploaded by you"); ?></span>
            <?php } elseif($product->getPropertyApproved() == 0) { ?>
       <span class="property-error"
            ><?php echo __("Awaiting for admins approval"); ?></span>
            <?php } ?>

    </div>
 </div>

        </div>
        <div class="clearfix"></div>

        <?php  $c ++;
            }
            echo $block->getPagerHtml ();
          } else { ?>
    <div class="norecords">
 <p class="no_transaction_records"><?php echo __('No Records Found'); ?></p>
        </div>
<?php } ?></div>

      </div>
             </div>
             <!-- Property List Ends-->
             <div class="clear"></div>
    </div>


           </div>
  </div>

         </div>
</div>
<script type="text/javascript">
    function airhotelsActivate(pStatus,buttonId,element)
    {

        document.getElementById(element).style.display = "none";
        document.getElementById("active"+buttonId).style.display ="none";
        document.getElementById("hide"+buttonId).style.display ="none";
        document.getElementById("loadingSpace"+buttonId).innerHTML = "<img style='margin-right:20px' src='<?php echo $this->getViewFileUrl('images/ajax-loader-small.gif'); ?>' />";
        var xmlhttp = getHttp();
        xmlhttp.onreadystatechange=function()
        {
            if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
              window.location.href = "";
            }
        }
        var productId = document.getElementById("productId"+buttonId).value;
        xmlhttp.open("GET","<?php echo $block->getUrl('airhotels/listing/status/') ?>"+"?status="+pStatus+"&buttonid="+buttonId+"&productid="+productId,true);
        xmlhttp.send();
    }
    function getHttp(){
        var xmlhttp;
        if (window.XMLHttpRequest)
        {
            xmlhttp=new XMLHttpRequest();
        }
        else
        {
            xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
        return xmlhttp;
    }

    function propertySearch(){
        var fromDate = jQuery("#propertyfrom").val();
        var toDate = jQuery("#propertyTo").val();
        if(fromDate == "" || fromDate == "yyyy-mm-dd" || toDate == "" || toDate == "yyyy-mm-dd"){
           alert('<?php echo __("Invalid dates, Please kindly check it."); ?>');
          return false;
        }
    }
    function clearForm(){
            jQuery("#propertyfrom").attr("value","yyyy-mm-dd");
            jQuery("#propertyTo").attr("value","yyyy-mm-dd");
            jQuery("#bookclear").attr("value","1");
    }
</script>