<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
$currencySymbol = $block->getCurrentCurrencySymbol ();
$priceSlider = $block->getPriceSlider ();
$productCategoryIds = array ();
$minValue = $maxValue = $rangeValue = "";
$minValue = $priceSlider ['minimum_price'];
if ($minValue == "" || $minValue <= 0) {
     $minValue = 0;
}
$maxValue = $priceSlider ['maximum_price'];
if ($maxValue == "" || $maxValue <= 0) {
     $maxValue = 5000;
}
$rangeValue = $priceSlider ['range_start'];
if ($rangeValue != "" && ($rangeValue - 50) >= $minValue) {
     $rangeValues = $rangeValue;
} else {
     $rangeValues = $maxValue;
}
$propertyServiceFromData = $this->getRequest ()->getParam ( 'property_service_from' );
$propertyServiceToData = $this->getRequest ()->getParam ( 'property_service_to' );
$propertyServiceFromPeriodData = $this->getRequest ()->getParam ( 'property_service_from_period' );
$propertyServiceToPeriodData = $this->getRequest ()->getParam ( 'property_service_to_period' );
$searchTextField = $this->getRequest ()->getParam ( 'q' );
$searchFromDate = $this->getRequest ()->getParam ( 'from' );
$searchToDate = $this->getRequest ()->getParam ( 'to' );
$numberOfGuest = $this->getRequest ()->getParam ( 'guests' );
$numberOfGuest = isset ( $numberOfGuest ) ? $numberOfGuest : '1';
$defaultLocation = $this->helper( 'Apptha\Airhotels\Helper\Data' )->getDefaultLocation ();
$demoNotice = $this->helper('Apptha\Airhotels\Helper\Dateformat')->displayDemoNotice();
$searchTextField = isset ( $searchTextField ) ? $searchTextField : (isset ( $defaultLocation ) ? $defaultLocation : __ ( "Berlin" ));
?>
<input type="hidden" name="searchAddress" id="searchAddress"
     value="<?php echo $searchTextField; ?>">
<?php $geoCode = $block->getGeocodeDatas($searchTextField); ?>
<script type="text/javascript">
require(["jquery","jquery/ui","moment","daterangepicker","form-map","markerlabel","responsiveslides","priceslider","searchmap"],
function(jQuery){
    jQuery(document).ready(function(){
        jQuery('#filter-popup').fancybox();
        jQuery("#guests").val("<?php echo $numberOfGuest ?>");
                var dates = jQuery("#fromcheckin,#tocheckin").datepicker({
            changeMonth: false,
            minDate: '0', numberOfMonths: 1,
            monthNames:["<?php echo __('January') ?>","<?php echo __('February') ?>","<?php echo __('March') ?>","<?php echo __('April') ?>","<?php echo __('May') ?>","<?php echo __('June') ?>","<?php echo __('July') ?>","<?php echo __('August') ?>","<?php echo __('September') ?>","<?php echo __('October') ?>","<?php echo __('November') ?>","<?php echo __('December') ?>"],
            onSelect: function( selectedDate ) {
                var option = this.id == "fromcheckin" ? "minDate" : "maxDate", instance = jQuery( this ).data( "datepicker" ),
                date = jQuery.datepicker.parseDate(
                instance.settings.dateFormat || jQuery.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );dates.not( this ).datepicker( "option", option, date );
                jQuery("#fromcheckin" ).datepicker("option","maxDate","");
                if(this.id == "fromcheckin"){ ajaxSearchResult('','','');
                    instance = jQuery( this ).data( "datepicker" )
                    var depart = jQuery.datepicker.parseDate(jQuery.datepicker._defaults.dateFormat, selectedDate);
                    depart.setDate(depart.getDate());
                    jQuery("#tocheckin" ).datepicker(  "option", "minDate", depart );
                }else{
                        ajaxSearchResult('','','');
                }
            }
        });
        jQuery("#pricePernight").slider({
            range: true, value:0,
            min:<?php echo $block->toCurrentCurrency($minValue); ?>,
            max: <?php echo $block->toCurrentCurrency($maxValue); ?>,
            step: <?php echo $block->toCurrentCurrency("100"); ?>,
            values: [0, <?php echo $block->toCurrentCurrency($rangeValue); ?> ],
            slide: function( event, ui ) {
                    if(parseInt(ui.values[0]) < parseInt(ui.values[1]) ){
                        startsPriceValueForSlider = parseInt(ui.values[0]);
                        endssPriceValueForSlider = parseInt(ui.values[1]);
                    jQuery( "#amountMin" ).val( "<?php echo $currencySymbol ?>" + ui.values[ 0 ] );
                    jQuery( "#amountMax" ).val( "<?php echo $currencySymbol; ?>" + ui.values[ 1 ] );
                    jQuery( "#pricepernightval" ).val(  ui.values[ 0 ] + "-" + ui.values[ 1 ] );
                }
            }
        });
        jQuery( "#pricePernight" ).on( "slidestop", function( event, ui ) {
        if(parseInt(ui.values[0]) < parseInt(ui.values[1]) ){
                    ajaxSearchResult('','','');
                }
                else{
                      jQuery("#pricePernight").slider({values:[startsPriceValueForSlider,endssPriceValueForSlider]});
                      return false;
                }
                 });
        function datechange(){
                 ajaxSearchResult('','','');
        }
        jQuery( "#amountMin" ).val( "<?php echo $currencySymbol ?>" + jQuery( "#pricePernight" ).slider( "values", 0 ));
        jQuery( "#amountMax" ).val( "<?php echo $currencySymbol ?>" + jQuery( "#pricePernight" ).slider( "values", 1) );
        jQuery( "#pricepernightval" ).val(  jQuery( "#pricePernight" ).slider( "values", 0 ) +"-" + jQuery( "#pricePernight" ).slider( "values", 1) );
        var textBack = jQuery("#expandAmenity").html();
        var texthide = jQuery("#amenityHide").val();
        jQuery("#expandAmenity").toggle(
                function show(){
                    jQuery("#searchAmenity").css({"height":"140px", });jQuery("#expandAmenity").html(jQuery("#amenityHide").val())
            },
                function hide(){jQuery("#expandAmenity").html(jQuery("#expandAmenity1").val())}
            );
        var textBack = jQuery("#expandHouseRules").html();
        var texthide = jQuery("#houseRulesHide").val();
        jQuery("#expandHouseRules").toggle(
                function show(){
                    jQuery("#searchHouseRules").css({"height":"140px", });jQuery("#expandHouseRules").html(jQuery("#houseRulesHide").val())
            },
                function hide(){jQuery("#expandHouseRules").html(jQuery("#expandHouseRules1").val())}
            );
        var textBack = jQuery("#expandHostLanguages").html();
        var texthide = jQuery("#hostLanguagesHide").val();
        jQuery("#expandHostLanguages").toggle(
                function show(){
                    jQuery("#searchHostLanguages").css({"height":"140px", });jQuery("#expandHostLanguages").html(jQuery("#hostLanguagesHide").val())
            },
                function hide(){jQuery("#expandHostLanguages").html(jQuery("#expandHostLanguages1").val())}
            );
        var textBack = jQuery("#expandProprType").html();
        var texthide = jQuery("#propertytypeHide1").val();
        jQuery("#expandProprType").toggle(
                        function show(){jQuery("#searchPropertytype").css({"height":"106px"});jQuery("#expandProprType").html(texthide)},
                  function hide(){jQuery("#searchPropertytype").css({"height":"11px"});jQuery("#expandProprType").html(textBack)}
                  );
        var textBack = jQuery("#expandSpot").html();
        var texthide = jQuery("#spotTypeHide1").val();
        jQuery("#expandSpot").toggle(
                        function show(){jQuery("#searchSpotType").css({"height":"106px"});jQuery("#expandSpot").html(texthide)},
                     function hide(){jQuery("#searchSpotType").css({"height":"11px"});jQuery("#expandSpot").html(textBack)}
             );
                /*** Expand the location and hide it.*/
            var textBackVal = jQuery("#expandLocation").html();
        var texthideVal = jQuery("#locationHide").val();
        jQuery("#expandLocation").toggle(
                         function show(){jQuery("#searchLocation").css({"height":"106px"});jQuery("#expandLocation").html(texthideVal)},
                     function hide(){jQuery("#searchLocation").css({"height":"11px"});jQuery("#expandLocation").html(textBackVal)}
              );
        var textBack = jQuery("#expandLocation").html();var texthide = jQuery("#locationHide").val();
        jQuery("#expandLocation").toggle(
                        function show(){jQuery("#searchLocation").css({"height":"106px"});jQuery("#expandLocation").html(texthide)},
                     function hide(){jQuery("#searchLocation").css({"height":"11px"});jQuery("#expandLocation").html(textBack)}
              );
        var textBack = jQuery("#expandWater").html();var texthide = jQuery("#waterHide").val();
        jQuery("#expandWater").toggle(
                        function show(){
                            jQuery("#searchWater").css({"height":"106px"});jQuery("#expandWater").html(texthide)
                            },
                     function hide(){
                             jQuery("#searchWater").css({"height":"11px"});jQuery("#expandWater").html(textBack)
                             }
              );
        var textBackValue = jQuery("#expandBestWind").html();
        var texthideValue = jQuery("#bestwindHide").val();
        jQuery("#expandBestWind").toggle(
                         function show(){jQuery("#searchBestWind").css({"height":"106px"});jQuery("#expandBestWind").html(texthideValue)},
                     function hide(){jQuery("#searchBestWind").css({"height":"11px"});jQuery("#expandBestWind").html(textBackValue)}
              );
        var textBak = jQuery("#expandWindDir").html();
        var texthid = jQuery("#winddirHide").val();
        jQuery("#expandWindDir").toggle(
                         function show(){jQuery("#searchWindDir").css({"height":"106px"});jQuery("#expandWindDir").html(texthid)},
                     function hide(){jQuery("#searchWindDir").css({"height":"11px"});jQuery("#expandWindDir").html(textBak)}
              );
        jQuery("#expandFilter").toggle(
                function show(){
            jQuery(".hideelements").hide();
            jQuery("#expandFilter").html("<?php echo __('Show Filters') ?>");
            if(jQuery(window).width() < 1024){
                                 jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
                        }else{
                    jQuery('.searchform-container #searchinnerpage').css({'margin-top':'13em'});
                        }
        },
        function hide(){
            jQuery(".hideelements").show();
            jQuery("#expandFilter").html("<?php echo __('Hide Filters') ?>");
            if(jQuery(window).width() < 1024){
                                 jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
                        }else{
            jQuery('.searchform-container #searchinnerpage').css({'margin-top':'24em'});
                        }
        }
    );
        jQuery(":checkbox").click(function(){
            getCheckboxVal();
            ajaxSearchResult('','','');
        });
    });
});
    var roomtypeVal ;
    var categoryVal ;
    var amenityVal ;
    var houseRulesVal ;
    var hostLanguagesVal ;
    var spotVal;
    var waterVal;
    function getCheckboxVal(){
            proptypeVal="";
             jQuery("[name='pro_type']:checked").each(function(){
             proptypeVal += jQuery(this).val() +"," ;
         })
         if(proptypeVal.length)
             proptypeVal = proptypeVal.substr(0,proptypeVal.length-1);
         roomtypeVal = "";
        jQuery("[name='room_type']:checked").each(function(){
            roomtypeVal += jQuery(this).val() +"," ;
        })
        if(roomtypeVal.length)
            roomtypeVal = roomtypeVal.substr(0,roomtypeVal.length-1);
        categoryVal = "";
        jQuery("[name='category_ids[]']:checked").each(function(){
                categoryVal += jQuery(this).val() +"," ;
        })
        if(categoryVal.length)
                categoryVal = categoryVal.substr(0,categoryVal.length-1);
        amenityVal = "";
        jQuery("[name='amenity']:checked").each(function(){
            amenityVal += jQuery(this).val() +"," ;
        })
        if(amenityVal.length)
            amenityVal = amenityVal.substr(0,amenityVal.length-1);
        houseRulesVal = "";
        jQuery("[name='house_rules']:checked").each(function(){
                houseRulesVal += jQuery(this).val() +"," ;
        })
        if(houseRulesVal.length)
                houseRulesVal = houseRulesVal.substr(0,houseRulesVal.length-1);
        hostLanguagesVal = "";
        jQuery("[name='host_languages']:checked").each(function(){
                hostLanguagesVal += jQuery(this).val() +"," ;
        })
        if(hostLanguagesVal.length)
                hostLanguagesVal = hostLanguagesVal.substr(0,hostLanguagesVal.length-1);
            spotVal = "";
            jQuery("[name='spot']:checked").each(function(){
                    spotVal += jQuery(this).val() +"," ;
            })
            if(spotVal.length)
                    spotVal = spotVal.substr(0,spotVal.length-1);

            waterVal = "";
            jQuery("[name='water']:checked").each(function(){
                    waterVal += jQuery(this).val() +"," ;
            })
            if(waterVal.length)
                    waterVal = waterVal.substr(0,waterVal.length-1);

            locationVal = "";
            jQuery("[name='location']:checked").each(function(){
                    locationVal += jQuery(this).val() +"," ;
            })
            if(locationVal.length)
                    locationVal = locationVal.substr(0,locationVal.length-1);
            bestwindVal = "";
            jQuery("[name='bestwind']:checked").each(function(){
                    bestwindVal += jQuery(this).val() +"," ;
            })
            if(bestwindVal.length)
                    bestwindVal = bestwindVal.substr(0,bestwindVal.length-1);

            winddirVal = "";
            jQuery("[name='winddir']:checked").each(function(){
                    winddirVal += jQuery(this).val() +"," ;
            })
            if(winddirVal.length)
                    winddirVal = winddirVal.substr(0,winddirVal.length-1);
            }
            function ajaxSearchResult(pageno, center, zoomLevel){
                getCheckboxVal();
                if(typeof pageno =="undefined"){
                    var pageno = 1;
                }else if(pageno==''){
                          var pageno = 1;
                }
                if((searchAddress != '') && (center == '')) {
                      var addressSearch='yes';
                }else{
                        var addressSearch='no';
                }
                var xhr;
                jQuery("#searchinnerpage").html('<div class="loadingWrapper"><div class="content three-bounce"><div class="one"></div><div class="two"></div><div class="three"></div></div></div>');
                var searchAddress = jQuery("#searchTextField").val();
                var searchAddressFrom = jQuery("#searchAddress").val();
                var checkin =  "<?php echo $searchFromDate; ?> ";
                var checkout = "<?php echo $searchToDate; ?> ";
                var searchguest = jQuery("#guests").val();
                var amount = jQuery("#pricepernightval").val();
                var upperLimitPrice = jQuery("#upperLimitPrice").val();
                var propertyServiceFrom = jQuery("#property_service_from").val();
                var propertyServiceTo = jQuery("#property_service_to").val();
                var propertyServiceFromPeriod = jQuery("#property_service_from_period").val();
                var propertyServiceToPeriod = jQuery("#property_service_to_period").val();
                if(center == "" || center=="undefined") {
                           center = '';
                    } else {
                            var searchAddress = '';
                    }
                    if(xhr && xhr.readystate != 4) {
                        xhr.abort();
                    }
                xhr = jQuery.ajax({
            async:true,
            type: "GET",
            data: {searchAddress :searchAddress,searchAddressFrom: searchAddressFrom,checkin:checkin,checkout:checkout,searchguest:searchguest,amount:amount,proptypeVal:proptypeVal,roomtypeval:roomtypeVal,categoryVal:categoryVal,amenityval:amenityVal,houseRulesval:houseRulesVal,hostLanguagesval:hostLanguagesVal,spotval:spotVal,locationval:locationVal,waterval:waterVal,bestwindval:bestwindVal,winddirval:winddirVal,pageno:pageno,upperLimitPrice:upperLimitPrice,propertyServiceFrom:propertyServiceFrom,propertyServiceTo:propertyServiceTo,propertyServiceFromPeriod:propertyServiceFromPeriod,propertyServiceToPeriod:propertyServiceToPeriod,latituteZoom:center,zoomLevel:zoomLevel},
            url: "<?php echo $block->getBaseUrl() . 'booking/listing/result' ?>",
            success: function(data){
                jQuery("#searchinnerpage").html(data);
                var prevCount  = jQuery('#prerescount').val();
                var rescount = jQuery('#rescount').val();
                if(prevCount != rescount) {
                jQuery('#prerescount').val(rescount);
                var alldata = '';
                var liwrapper = jQuery("#results").find('li');

                if(liwrapper.length > 0) {
                           var propertyprice = [];
                   for(l=0; l<liwrapper.length; l++) {
                     property_name = jQuery(liwrapper[l]).attr("data-name");
                     property_location = jQuery(liwrapper[l]).attr("data-location");
                     property_location = property_location.replace(",", "#@@A");
                     property_price = jQuery(liwrapper[l]).attr("currency-data");
                     propertyprice.push(property_price);
                     property_url = jQuery(liwrapper[l]).attr("data-url");
                     property_src = jQuery(liwrapper[l]).attr("data-src");
                     property_state = jQuery(liwrapper[l]).attr("data-state");
                     product_id = jQuery(liwrapper[l]).attr("product_id");
                     if((property_name != '') && (property_location != '') && (property_url != '') && (property_src != '')) {
                     alldata += property_url+'#@@A'+property_src+'#@@A'+property_state+'#@@A'+property_name+'#@@A'+property_location+'#@@A'+property_price+'#@@A'+product_id+'@|@';
                     }
                   }
                   }else {
                       alldata = jQuery('#searchTextField').val();
                   }
                    jQuery("#latlong_cordinates").val(alldata);
                        var cordinate_value = jQuery('#latlong_cordinates').val();

                         var northeastlat = '<?php echo $geoCode['northeastlat']; ?>';
                         var northeastlng = '<?php echo $geoCode['northeastlng']; ?>';
                         var southwestlat = '<?php echo $geoCode['southwestlat']; ?>';
                         var southwestlng = '<?php echo $geoCode['southwestlng']; ?>';
                         loadmarkers(cordinate_value,zoomLevel,addressSearch,propertyprice,northeastlat,northeastlng,southwestlat,southwestlng);
                            }
               }
           });
    }
</script>
<?php
$accDefault = 16;
$select = "";
$privacySelect = '';
$helper = $this->helper('Apptha\Airhotels\Helper\General')->getPropertyDetails();
$helperAttribute = $this->helper('Apptha\Airhotels\Helper\General')->getAttributeDetails();
$propertytypeId = $helper->getpropertytype ();
$propertytypeAttribute = $helperAttribute->getAttribute ( 'catalog_product', $propertytypeId );
$amenityId = $helper->getamenity ();
$amenityAttribute = $helperAttribute->getAttribute ( 'catalog_product', $amenityId );
$hostLanguagesId = $helper->getHostLanguages ();
$hostLanguagesAttribute = $helperAttribute->getAttribute ( 'catalog_product', $hostLanguagesId );
$houseRulesId = $helper->getHouseRules ();
$houseRulesAttribute = $helperAttribute->getAttribute ( 'catalog_product', $houseRulesId );
$privacyId = $helper->getprivacy ();
$privacyAttribute = $helperAttribute->getAttribute ( 'catalog_product', $privacyId );
foreach ( $privacyAttribute->getSource ()->getAllOptions () as $privacyOption ) {
     $privacyValue = $privacyOption ['value'];

     if ($privacyValue != '') {
          $privacySelect .= "<li><em class='airhotel-sprite'></em><div class='ckbox'><input type='checkbox' name='room_type' id='room_type' value='" . $privacyOption ['value'] . "'><label class='check-box'>" . $privacyOption ['label'] . "</label></div><li/>";
     }
}
?>
<input type="hidden" id="upperLimitPrice"
     value="<?php echo $block->toCurrentCurrency($maxValue); ?>" />
<div class="advanced-mapsearch clearfix">
     <div class="map-container <?php if ($this->customerSession->isLoggedIn()) {  ?>user<?php } ?>">
          <div class="mapsearchCtrl">
               <input type="checkbox" name="searchmap" id="searchmap" checked
                    value="1" /> <label for="searchmap"><?php echo __('Search when I move the map')?></label>
          </div>
          <div id="mapview">
               <div id="map">
                   <div class="loadingWrapper"><div class="content three-bounce"><div class="one"></div><div class="two"></div><div class="three"></div></div></div>
               </div>
          </div>
          <input type="hidden" id="latlong_cordinates" value="">
     </div>
     <div
          class="searchform-container <?php if ($this->customerSession->isLoggedIn()) { ?>user<?php } ?>">
          <div class="mob_show_filter <?php if ($demoNotice){  ?> noticed <?php } ?> ">
            <ul class="filter-map">
                <li>
                    <a href="#filter-content" id="filter-popup">
                          <?php echo __('Show Filter')?>
                          <svg class="ic-filter"><use xlink:href='<?php echo $this->getViewFileUrl('images/sprite.svg#filter'); ?>'></svg>
                    </a>
                </li>
                <li class="listing-mapcanvas">
                    <span class="ic-maplocation map-view"></span>
                </li>
                </ul>
          </div>
          <div class="searchmainpage_1 <?php if ($demoNotice){  ?> noticed <?php } ?> " id="filter-content">
               <ul class="gradient-grey left">
                    <li class="advance_date" id="advance_date_room"><label
                         id="democheck-one" for="room" class="span_head room_type"
                         onclick="demoone(this)"><span> <?php echo __('Room Type'); ?></span>
                    </label>
                         <div class="in_out_dates" style="display: none;">
                              <ul>
                                    <?php echo $privacySelect;?>
                              </ul>
                         </div></li>
                            <?php
     /**
      * Get categories
      */
     $helperCategories = $this->helper('Apptha\Airhotels\Helper\General')->getSearchCategory();
     $categories = $helperCategories->getStoreCategories ( true, false, true );
     ?>
                                <li class="airhotels-category-type"><label
                         id="democheck" onclick="demo(this)" for="category"
                         class="label category-label span_head"><span><?php echo __('Categories'); ?></span></label>
                         <div class="block-category" style="display: none">
                <?php
                   /*** Check the Categories is not equal to empty*/
                                                                                if (! empty ( $categories )) {
                                                                                     echo $helperCategories->alphabaticalOrder ( $categories, $productCategoryIds );
                                                                                }
                                                                                ?>
                            </div></li>
                    <li class="left" class="pricerange" id="pricerange"><label
                         id="pricerange-booking" class="span_head price_type"
                         onclick="pricerng(this)"> <span class="span_head"> <?php echo __('Price'); ?> </span></label>
                         <div class="price_min_max" style="display: none;">
                              <div class="advance_price_slider">
                                   <span class="price-slider-left"> <input type="text"
                                        id="amountMin" readonly />
                                   </span>
                                   <div id="pricePernight"></div>
                                   <span class="price-slider-right"> <input type="hidden" value=""
                                        id="pricepernightval" /> <input type="text" id="amountMax"
                                        readonly />
                                   </span>
                              </div></li>
                    <input type="hidden" class="left searchmainpage"
                         value="<?php $placeholder = __ ( 'Where do you want to eat ?' );
                         if ($placeholder != $searchTextField) {
                              echo $searchTextField;
                         }
                         ?>"
                         id="searchTextField" name="searchTextField" type="text"
                         class="searchmainpage"
                         placeholder="<?php echo __('e.g. Berlin, Los Angeles'); ?>"
                         id="searchTextField" name="searchTextField" type="text"
                         class="searchmainpage"
                         placeholder="<?php echo __('e.g. Berlin, Los Angeles'); ?>"
                         onfocus="if (this.placeholder == '<?php echo __('e.g. Berlin, Los Angeles'); ?>') {this.placeholder = '';this.style.color ='#8AA443';}"
                         onblur="if (this.placeholder == '') {this.style.color ='#8AA443';this.placeholder = '<?php echo __('e.g. Berlin, Los Angeles'); ?>';}">
                    <li class="listing-filters">
                         <div class="show_filter" id="show_filter"
                              onclick="searchfilter(this)">
                              <span class="span_head"><?php echo __('Show Filters'); ?></span>
                         </div>
                         <div class="advance_srch" style="display: none">
                              <div class="advance_date" id="property_type">
                                   <span class="span_head"><?php echo __('Property type'); ?></span>
                                   <div class="in_out_date">
                                <?php
$totalPropertytype = count ( $propertytypeAttribute->getSource ()->getAllOptions () );
                         if ($totalPropertytype > 4) {
                              ?>
                                    <div id="expandProprType" style="cursor: pointer"><?php echo __('More') . ".." ?></div>
                            <?php } ?>
                            <ul id="searchPropertytype">
                        <?php
                                                                                                                        foreach ( $propertytypeAttribute->getSource ()->getAllOptions () as $propertytype ) {
                                                                                                                             $propertyname = explode ( '@/@', $propertytype ['label'] );
                                                                                                                             $propertytype ['label'] = $propertyname [0];
                                                                                                                             $value = $propertytype ['value'];
                                                                                                                             if ($value != '') {
                                                                                                                                  $PropertyType [$value] = $propertytype ['label'];
                                                                                                                                  ?>
             <li><div class='ckbox'>
<input type="checkbox" name="pro_type" value="<?php echo $propertytype['value']; ?>" />
<label class="checkboxspan check-box"> <?php echo ucfirst($propertytype['label']); ?></label>
                                                  </div></li>
                                <?php
                                                                                                                             }
                                                                                                                        }
                                                                                                                        ?>
                    </ul>
                                        <input type="hidden" value="<?php echo __('Hide'); ?>.."
                                             id="propertytypeHide" /> <input type="hidden"
                                             value="<?php echo __('More'); ?>.." id="expandProprType1" />
                                   </div>
                              </div>
                              <div class="advance_date" id="amenities">
                                   <span class="span_head"><?php echo __('Amenities'); ?></span>
                                   <div class="in_out_date">
                                        <?php
                                                                 $totalAmenity = count ( $amenityAttribute->getSource ()->getAllOptions () );
                                                                 if ($totalAmenity > 4) {
                                                                      ?>
                                        <div id="expandAmenity"
                                             style="cursor: pointer"><?php echo __('More') . ".." ?></div>
                                <?php } ?>
                             <ul id="searchAmenity"overflow:hidden" >
                                <?php
                         foreach ( $amenityAttribute->getSource ()->getAllOptions () as $amenity ) {
                              $amenityname = explode ( '@/@', $amenity ['label'] );
                              $amenity ['label'] = $amenityname [0];
                              $value = $amenity ['value'];
                              if ($value != '') {
                                   $PropertyType [$value] = $amenity ['label'];
                                   ?>
                                        <li><div class='ckbox'>
                                                       <input type="checkbox" name="amenity" value="<?php echo $amenity['value']; ?>" /><label
                                                            class="checkboxspan check-box"> <?php echo ucfirst($amenity['label']); ?></label>
                                                  </div></li>
                                        <?php
                              }
                         }
                         ?>
                            </ul>
                                        <input type="hidden" value="<?php echo __('Hide'); ?>.." id="amenityHide" /> <input type="hidden" value="<?php echo __('More'); ?>.." id="expandAmenity1" />
                                   </div>
                              </div>
                              <div class="advance_date" id="house_rules">
                                   <span class="span_head"><?php echo __('House Rules'); ?></span>
                                   <div class="in_out_date">
                                        <?php
                                                                 $totalHouseRules = count ( $houseRulesAttribute->getSource ()->getAllOptions () );
                                                                 if ($totalHouseRules > 4) {
                                                                      ?>
                                        <div id="expandHouseRules"
                                             style="cursor: pointer"><?php echo __('More') . ".." ?></div>
                                <?php } ?>
                             <ul id="searchHouseRules"overflow:hidden" >
                                <?php
                         foreach ( $houseRulesAttribute->getSource ()->getAllOptions () as $houseRules ) {
                              $houseRulesName = explode ( '@/@', $houseRules ['label'] );
                              $houseRules ['label'] = $houseRulesName [0];
                              $value = $houseRules ['value'];
                              if ($value != '') {
                                   $PropertyType [$value] = $houseRules ['label'];
                                   ?>
                                        <li><div class='ckbox'>
                                                       <input type="checkbox" name="house_rules" value="<?php echo $houseRules['value']; ?>" />
                                                       <label class="checkboxspan check-box"> <?php echo ucfirst($houseRules['label']); ?></label>
                                                  </div></li>
                                        <?php
                              }
                         }
                         ?>
                            </ul>
                                        <input type="hidden" value="<?php echo __('Hide'); ?>.." id="houseRulesHide" /> <input type="hidden" value="<?php echo __('More'); ?>.." id="expandHouseRules1" />
                                   </div>
                              </div>
                              <div class="advance_date" id="host_languages">
                                   <span class="span_head"><?php echo __('Host Languages'); ?></span>
                                   <div class="in_out_date">
                                        <?php
                                                                 $totalHostLanguages = count ( $hostLanguagesAttribute->getSource ()->getAllOptions () );
                                                                 if ($totalHostLanguages > 4) {    ?>
                                        <div id="expandHostLanguages"
                                             style="cursor: pointer"><?php echo __('More') . ".." ?></div>
                                <?php } ?>
                             <ul id="searchHouseLanguages"overflow:hidden" >
                                <?php
                         foreach ( $hostLanguagesAttribute->getSource ()->getAllOptions () as $hostLanguages ) {
                              $hostLanguagesName = explode ( '@/@', $hostLanguages ['label'] );
                              $hostLanguages ['label'] = $hostLanguagesName [0];
                              $value = $hostLanguages ['value'];
                              if ($value != '') {
                                   $PropertyType [$value] = $hostLanguages ['label'];
                                   ?>
                                        <li><div class='ckbox'><input type="checkbox" name="host_languages" value="<?php echo $hostLanguages['value']; ?>" />
                                                       <label class="checkboxspan check-box"> <?php echo ucfirst($hostLanguages['label']); ?></label><div class='ckbox'></li>
                                        <?php
                              }
                         }
                         ?>
                            </ul>
                                        <input type="hidden" value="<?php echo __('Hide'); ?>.." id="hostLanguagesHide" /> <input type="hidden" value="<?php echo __('More'); ?>.." id="expandHostLanguages1" />
                                   </div>
                              </div>
                         </div>
                    </li>
                    <li class="listing-mapcanvas">
                        <span class="ic-maplocation map-view"></span>
                    </li>
               </ul> 
   <div class="filter-apply-btn"><button type="button" onClick="closeBox();"><?php echo __('Apply');?></button>
   </div>
          </div>
          <div class="clear temp"></div>
          <div id="searchinnerpage" style="min-height: 210px;">
               <input type="hidden" id="active_view" value="searchinnerpage"> <input
                    type="hidden" name="latlong_cordinates" id="latlong_cordinates" /> <input
                    type="hidden" name="prerescount" id="prerescount" value="" />
          </div>
     </div>
</div>
<script type="text/javascript">
    function closeBox(){    
    jQuery.fancybox.close();
    ajaxSearchResult();
}
function demo(a){
    if(a.id == 'democheck') {
    jQuery(".block-category").show();
    jQuery(".in_out_dates").hide();
    jQuery(".price_min_max").hide();
    jQuery(".advance_srch").hide();
        jQuery('.category-label').attr('id', 'added');
    } else{
    jQuery(".block-category").hide();
    jQuery('.category-label').attr('id', 'democheck');
    }
}
function demoone(a){
    if(a.id == 'democheck-one') {
    jQuery(".in_out_dates").show();
    jQuery(".block-category").hide();
    jQuery(".price_min_max").hide();
    jQuery(".advance_srch").hide();
        jQuery('.room_type').attr('id', 'demo-one');
    } else{
    jQuery(".in_out_dates").hide();
    jQuery('.room_type').attr('id', 'democheck-one');
    }
}
function pricerng(a){
    if(a.id == 'pricerange-booking') {
    jQuery(".price_min_max").show();
    jQuery(".in_out_dates").hide();
    jQuery(".block-category").hide();
    jQuery(".advance_srch").hide();
        jQuery('.price_type').attr('id', 'price-rng');
    } else{
    jQuery(".price_min_max").hide();
    jQuery('.price_type').attr('id', 'pricerange-booking');
    }
}
function searchfilter(a){
    if(a.id == 'show_filter') {
    jQuery(".price_min_max").hide();
    jQuery(".in_out_dates").hide();
    jQuery(".block-category").hide();
    jQuery(".advance_srch").show();
        jQuery('.show_filter').attr('id', 'show_filter_hide');
    } else{
    jQuery(".advance_srch").hide();
    jQuery('.show_filter').attr('id', 'show_filter');
    }
}
</script>
<script type="text/javascript">
require(["jquery","jquery/ui","moment","daterangepicker","form-map","markerlabel","responsiveslides","priceslider","searchmap"
        ], function(jQuery){
jQuery(document).ready(function(){
     jQuery('.airhotels-category-type').click(function(e){
          e.stopPropagation();
          if(e.srcElement.id == 'democheck') {
            jQuery(".block-category").show();
            jQuery('.category-label').attr('id', 'added');
          jQuery('#advance_date_room .in_out_dates').hide();
          jQuery('#pricerange .price_min_max').hide();
          jQuery(".advance_srch").hide();
          jQuery(".show_filter").html("<?php echo __('Show Filters'); ?>");
          }
     });
  jQuery('#advance_date_room').click(function(e){
          e.stopPropagation();
          if(e.srcElement.id == 'democheck-one') {
            jQuery(".in_out_dates").show();
            jQuery('.room_type').attr('id', 'demo-one');
          jQuery('.airhotels-category-type .block-category').hide();
          jQuery('#pricerange .price_min_max').hide();
          jQuery(".advance_srch").hide();
          jQuery(".show_filter").html("<?php echo __('Show Filters'); ?>");
          }
     });
          jQuery('#pricerange').click(function(e){
          e.stopPropagation();
          if(e.srcElement.id== 'pricerange-booking') {
                 jQuery(".price_min_max").show();
                 jQuery('.price_type').attr('id', 'price-rng');
          jQuery('#advance_date_room .in_out_dates').hide();
          jQuery('.airhotels-category-type .block-category').hide();
          jQuery(".advance_srch").hide();
          jQuery(".show_filter").html("<?php echo __('Show Filters'); ?>");
          }
     });
jQuery(".show_filter").click(function(e) {
    e.stopPropagation();
if(jQuery(".show_filter").text()=="<?php echo __('Show Filters'); ?>"){
        jQuery(".advance_srch").show();
        jQuery(".block-category").hide();
        jQuery("#advance_date_room .in_out_dates").hide();
        jQuery(".price_min_max").hide();
        jQuery(".show_filter").html("<?php echo __('Hide Filters') ?>");
        }else{
        jQuery(".advance_srch").hide();
        jQuery(".show_filter").html("<?php echo __('Show Filters'); ?>");
        }
        });
     jQuery(document).click(function(e){
          e.stopPropagation();
          jQuery('#pricerange .price_min_max').hide();
          jQuery('.price_type').attr('id', 'pricerange-booking');
          jQuery('#advance_date_room .in_out_dates').hide();
          jQuery('.room_type').attr('id', 'democheck-one');
          jQuery('.airhotels-category-type .block-category').hide();
          jQuery('.category-label').attr('id', 'democheck');
          if(e.toElement.accept != ""){
             jQuery(".advance_srch").hide();
             jQuery(".show_filter").html("<?php echo __('Show Filters'); ?>");
           }
          });
     initialLoad();
    ajaxSearchResult('','','');
    function initialLoad(){
                 jQuery('.header-container').addClass('top-fix');
        jQuery('.map-container').addClass('fixed-position');
        var center;
        var zoomvalue;
        var mapOptions = {zoom: 12,center: new google.maps.LatLng(46.613071, 1.543322),mapTypeId: google.maps.MapTypeId.ROADMAP};
        var map = new google.maps.Map(document.getElementById('map'),
        mapOptions);
        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.SearchBox(input);
        autocomplete.bindTo('bounds', map);
        function setupClickListener(id, types) { var radioButton = document.getElementById(id); google.maps.event.addDomListener(radioButton, 'click', function() { autocomplete.setTypes(types); });}
    }
    jQuery('.ic-maplocation').click(function(){
     ajaxSearchResult();
   });
        if(jQuery(window).width() < 1024){
                jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
        }else{
                jQuery(window).scroll(function() {
                        if(jQuery(window).width() < 1024){
                                 jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
                        }else{
                       var scrollVal = jQuery(this).scrollTop();
                        if ( scrollVal > 50) {
                                jQuery(".hideelements").hide();
                            jQuery("#expandFilter").html("<?php echo __('Show Filters'); ?>")
                            jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
                        } else {
                                 jQuery(".hideelements").show();
                              jQuery("#expandFilter").html("<?php echo __('Hide Filters') ?>")
                              jQuery('.searchform-container #searchinnerpage').css({'margin-top':'0em'});
                        }
                        }
                });
        }
});
});
</script>
<script type="text/javascript">
var markers = [];
var testValue = [];
var constantzoomLevel = '';
var constantzoomLevelStatus = 0;
var zoomLatitude = [];
function loadmarkers(co_ordinates, prezoomlevel, addressSearch,price, northeastlat, northeastlng, southwestlat,southwestlng) {
     var disableListener = true;
     var latitudeCount;
     var defaultlat;
     var defaultlng;
     var center;
     var co_ordinates_trimed = co_ordinates;
     var locations = [];
     var coordinates = [];
     var datapoints = co_ordinates_trimed.split('@|@');
     var product_id;
     if (datapoints.length > 1) {
          latitudeCount = 'm';
          for (k = 0; k < (datapoints.length - 1); k++) {
               var temp = datapoints[k].split('#@@A');
               var details = '<div class="search-result-container"><a href="'
                         + temp[0]
                         + '" title="'
                         + temp[3]
                         + '"  class="matte2-media-box rslides1" style="text-decoration:none; text-transform:capitalize;"><div class="slider_showface"><img src="'
                         + temp[1]
                         + '" width="220" height="180"><div class="map-price">'
                         + temp[6]
                         + '</div></div><div class="data-details"><h4>'
                         + temp[3]
                         + '</h4><h3>'
                         + temp[2]
                         + '</h3></div></a></div>';
               var coordinates = [ details, temp[4], temp[5], temp[7] ];
               locations.push(coordinates);
          }
          product_id = temp[7];
          defaultlat = temp[4];
          defaultlng = temp[5];
     } else {
          disableListener = false;
          latitudeCount = 's';
          var coordinatesvalues = jQuery('#default_map_location')
                    .html();
          var datapointsdefault = coordinatesvalues.split('@|@');
          var details = '';
          var coordinates = [ details, datapointsdefault[0],
                    datapointsdefault[1], datapointsdefault[2] ];
          locations.push(coordinates);
          defaultlat = datapointsdefault[0];
          defaultlng = datapointsdefault[1];
     }
     var iconURLPrefix = 'http://maps.google.com/mapfiles/ms/icons/';
     var icons = [ iconURLPrefix + 'red-dot.png',
               iconURLPrefix + 'green-dot.png',
               iconURLPrefix + 'blue-dot.png',
               iconURLPrefix + 'orange-dot.png',
               iconURLPrefix + 'purple-dot.png',
               iconURLPrefix + 'pink-dot.png',
               iconURLPrefix + 'yellow-dot.png' ]
     var icons_length = icons.length;
     var minzoomlevel;
     if (prezoomlevel) {
          minzoomlevel = prezoomlevel;
     } else {
          minzoomlevel = 1;
     }
     var map = new google.maps.Map(document.getElementById('map'), {
          minZoom : minzoomlevel, maxZoom : 18, scrollwheel : false,
          center : new google.maps.LatLng(defaultlat, defaultlng),
          mapTypeId : google.maps.MapTypeId.ROADMAP, mapTypeControl : false,streetViewControl : false,panControl : false,
          zoomControlOptions : {
               position : google.maps.ControlPosition.TOP_LEFT
          }
     });
     disableListener = true;
     var zoommode = 'off';
     var mapZoomLevelStatusC = '';
     var listener1 = google.maps.event
               .addListener(
                         map,
                         'zoom_changed',
                         function() {
                              var center = map.getCenter();
                              if (disableListener == false) {
                                   if (zoommode == 'on') {
                                        var zoomLatLong = map.getCenter()
                                                  .toString();
                                        zoomLatLong = zoomLatLong.replace(
                                                  "(", "").replace(")", "")
                                                  .replace(", ", ",");
                                        var zoomLevel = map.getZoom();
                                        if (jQuery('#searchmap:checked')
                                                  .val() == 1) {
                                             ajaxSearchResult('',
                                                       zoomLatLong, zoomLevel);
                                        }
                                   }
                              }
                         });
     google.maps.event.addListener(map, 'dragend', function() {
          if (zoommode == 'on') {
               var zoomLatLong = map.getCenter().toString();
               zoomLatLong = zoomLatLong.replace("(", "").replace(")",
                         "").replace(", ", ",");
               var zoomLevel = map.getZoom();
               if (jQuery('#searchmap:checked').val() == 1) {
                    ajaxSearchResult('', zoomLatLong, zoomLevel);
               }
          }
     });
     if (latitudeCount != 's') {
          var infowindow = new google.maps.InfoWindow();
          var marker, i, j;
          var markers = new Array();
          var iconCounter = 0;
          for (i = 0; i < locations.length; i++) {
               var pidForMarker = locations[i][3];
               testValue[pidForMarker] = marker = new MarkerWithLabel(
                         {
                              position : new google.maps.LatLng(
                                        locations[i][1], locations[i][2]),
                              map : map,
                              labelContent : price[i],
                              labelAnchor : new google.maps.Point(22, 0),
                              labelClass : "labels", // the CSS class for
                              labelStyle : {
                                   opacity : 0.75
                              },
                              id : 'map_pin_' + locations[i][3],
                              icon : 'images/transparent-1x1.png'
                         });
               markers.push(marker);
               google.maps.event.addListener(map, 'click', function(
                         event) {
                    infowindow.close();
               });
               google.maps.event.addListener(marker, 'click',
                         (function(marker, i) {
                              return function() {
                                   infowindow.setContent(locations[i][0]);
                                   infowindow.open(map, marker);
                              }
                         })(marker, i));
               google.maps.event.addListener(marker, 'mouseover',
                         (function(marker, i) {
                              return function() {
                                   jQuery(  "#product_map_over_" + locations[i][3])
                                             .addClass("active");
                              }
                         })(marker, i));
               google.maps.event.addListener(marker, 'mouseout',
                         (function(marker, i) {
                              return function() {
                                   jQuery("#product_map_over_" + locations[i][3]).removeClass("active");
                              }
                         })(marker, i));
          }
          var bounds = new google.maps.LatLngBounds(
                    new google.maps.LatLng(southwestlat, southwestlng),
                    new google.maps.LatLng(northeastlat, northeastlng));
          jQuery.each(markers, function(index, marker) {
               bounds.extend(marker.position);
          });
          var center = bounds.getCenter();
          var x = bounds.contains(center);
          map.setCenter(bounds.getCenter());
          map.fitBounds(bounds);
     } else {
          var bounds = new google.maps.LatLngBounds(
                       new google.maps.LatLng(southwestlat, southwestlng),
                       new google.maps.LatLng(northeastlat, northeastlng));
          var center = bounds.getCenter();
          var x = bounds.contains(center);
          map.setCenter(bounds.getCenter());
          map.fitBounds(bounds);
     }
     disableListener = false;
}
function hintMarkerInMap(value) {
}
function outHintMarkerInMap(value) {
}
</script>

<script type="text/javascript">
   require(["jquery","jquery/ui",], function($){
$(document).ready(function(){
    $(".airhotels-listing-search").addClass("fancy-popup");
});
});
</script>