<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$currentCustomerData = $this->getCustomerDetails ();
$customer = $this->getCustomerData ();
$customerProfileData = $this->getCustomerProfileData ();
$customerMonth = date ( "F", strtotime ( $customer->getCreatedAt () ) );
$customerYear = date ( 'Y', strtotime ( $customer->getCreatedAt () ) );
$hostVerified = $this->getHostVerified ();
$listingCollection = $block->getMyListing ();
$currentStore = $this->helper('Apptha\Airhotels\Helper\Data')->getStore();
$baseUrl = $currentStore->getBaseUrl();
$_reviewCount = 0;
if(count($listingCollection) > 0 ){
    foreach ( $listingCollection as $listingCollections ) {
        $_ratingSummary = $block->getRatingSummary ( $listingCollections );
          $_reviewCount = $_reviewCount + $listingCollections->getRatingSummary ()->getReviewsCount ();

    }
    $_ratingSummary = $_ratingSummary?$_ratingSummary:0;
} else {
    $_ratingSummary = 0;
    $_reviewCount = 0;
    $listingCollection = array();
}


?>
<?php
$customerProfileDatas = $customerProfileData->getData();
$count = count($customerProfileDatas);
if($count == 0){ ?>
    <div class="my-account">
         <div class="page-title" style="margin: 0;">
            <div class="profile-details"><?php echo __('Please fill profile details to view the dashboard.')?> <span><?php echo __('Click below link to redirect to dashboard.') ?></span>
             <a href="<?php echo $block->getUrl('booking/profile/edit/');?>"><?php echo __('Profile') ?></a>
            </div>
        </div>
    </div>
<?php }else{?>
<div class="my-account">
     <div class="page-title" style="margin: 0;">
          <h2 class="account-heading"><?php echo __('Hey,I&#39;m '); ?>
        <span><?php echo $currentCustomerData->getName(); ?> !</span>
          </h2>
          <span class="member_since">
    <?php echo __($customerProfileData->getCity().', '.$customerProfileData->getCountry().' &#46; Joined in '); ?> <?php echo $customerMonth .' '.$customerYear;?></span>
     </div>
     <div class="body_grid clearfix">
          <div class="customer-profile-information">
<?php if(!empty($customerProfileData->getDescription())){ ?>
              <p><?php echo $customerProfileData->getDescription(); ?></p>
              <?php }else{?>
                  <p><?php

echo __ ( 'Hello, Im Natasha. Originally I am from Moscow, but for last 7 years I live in Budapest with my husband and 2 children.
I am photographer and guide a small family photo studio here. I love ancient stuff, in my flat you can enjoy the design
of turn-of-the-century Budapest through old decoration elements you can find here. Welcome .' );
    ?></p>

              <?php } ?>
              <div class="review-verify">
                    <ul>
                         <li><span class="reviews-count"><?php  echo $_reviewCount; ?></span><span><?php echo __('Reviews')?></span></li>
                         <?php if($hostVerified->getHostTags()==0):?>
                           <li><span class="verify-icon pending"><?php echo __('Pending');?></span></li>
                         <?php elseif($hostVerified->getHostTags()==1):?>
                           <li><span class="verify-icon verified"><?php echo __('Verified');?></span></li>
                         <?php else:?>
                           <li><span class="verify-icon rejected"><?php echo __('Rejected');?></span></li>
                         <?php endif;?>
                    </ul>
               </div>
          </div>
          <div class="wishlist-reviews-listing">
               <ul>
                    <li>
                             <h3> <?php echo __('My Listings')?> <span>(<?php echo count($listingCollection);?>)</span></h3>
                          <ul class="mylistings-section">
            <?php foreach ( $listingCollection as $listingCollections ) {
                $productUrl = $currentStore->getBaseUrl ().$listingCollections->getUrlKey().'.html';
                $mediaUrl = $currentStore->getBaseUrl ( \Magento\Framework\UrlInterface::URL_TYPE_MEDIA ) . 'catalog/product' . $listingCollections->getImage ();
                $privacyType = $listingCollections->getAttributeText ( 'privacy' );
                $propertyType = $listingCollections->getAttributeText ( 'booking_type' );
                $bedType = $listingCollections->getAttributeText ( 'bedtype' );
                $value = $listingCollections->getPrice ();
                $listingPrice = $this->helper('Apptha\Airhotels\Helper\General')->priceConverter($value);
                $_ratingSummary = $block->getRatingSummary ( $listingCollections );
                $_ratingSummary = $_ratingSummary?$_ratingSummary:0;
                $helper = $this->helper('Apptha\Airhotels\Helper\General');
                $placeholderUrl = $helper->getPlaceholderImage();
                ?>
                              <li><a href="<?php echo $productUrl;?>">
                                        <div class="mylisting-image">
                                             <div class="mylisting-image-img" style="background-image: url('<?php echo $listingCollections->getImage()?$mediaUrl:$placeholderUrl;?>')"></div>
                                        </div>
                                        <div class="mylisting-content">
                                             <h4><?php echo $listingCollections->getName();?></h4>
                                             <p><?php echo $privacyType;?>/<?php echo $propertyType;?>. <?php echo $bedType;?></p>
                                             <div class="rating-box">
                                                  <div class="rating" style="width:<?php echo $_ratingSummary;?>%;"></div>
                                             </div>
                                             <div class="price">
                                                  <h4><?php echo $listingPrice;?></h4>
                                             </div>
                                        </div>
                              </a></li>
<?php
            }
            ?>
            </ul>
         </li>
                    <li class="list-review">
                              <h3> <?php echo __('Listing Reviews')?><span>(<?php echo $_reviewCount;?>)</span></h3>
         <?php
         if ( $block->getRatingSummaryCollection()->count() > 0) {
             foreach ( $block->getRatingSummaryCollection() as $listingCollection ) {
              $profileImage = $block->getProfileImage($listingCollection);
               $getCustomerProfileImage=($profileImage)?$this->getCustomerProfileImage().$profileImage->getProfileimage(): $block->getViewFileUrl('Apptha_Airhotels::images/no_user.jpg');
                  ?>
              <div class="reviews-from-guest">
                              <ul>
                                   <li class="clearfix">
                                        <div class="guest-image-section">
                                             <div class="guest-image">
                                               <img src="<?php echo $getCustomerProfileImage?>" alt="profile">
                                             </div>
                                             <h5><?php echo $listingCollection['nickname'];?></h5>
                                        </div>
                                        <div class="guest-info">
                                        <h6><?php echo __('Review From: ')?><span><?php echo ($listingCollection->getCustomerId()!=Null)?$block->getCustomer($listingCollection->getCustomerId())->getName():'Administrator'; ?></span></h6>
                                             <p><?php echo $listingCollection['title'];?></p>
                                             <p><?php echo $listingCollection['detail'];?></p>
                                             <span class="guest-pace"><?php echo __('Posted On,')?> <?php echo date('d-m-Y',strtotime($listingCollection['created_at']));?>.</span>
                                        </div>
                                   </li>
                              </ul>
                         </div>
                  <?php
            }
        }
        ?>
        <?php if($_reviewCount==0){?>
            <div class="no_reviews"><?php echo __('Yet no reviews available')?></div>
         <?php }?>
        </li>
        <?php echo $block->getPagerHtml ();?>
   </ul>
          </div>
     </div>
     <div class="dashboard my_dashbd"></div>
</div>
<?php }?>
