<?php
/**
 * Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Airhotels
* @version     1.0.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/
$profileData=$this->getCustomerProfileData();
$getCusotmerData=$this->getCustomerDetails();
if(!empty($profileData->getProfileimage())){
     $getCustomerProfileImage=$this->getCustomerProfileImage().$profileData->getProfileimage();
}else{
     $getCustomerProfileImage=$block->getViewFileUrl('Apptha_Airhotels::images/no_user.jpg');
}
$listingDateFormat = $this->helper('Apptha\Airhotels\Helper\Dateformat')->getListingDateformat();
$convertedDateFormat = $this->helper('Apptha\Airhotels\Helper\Dateformat')->getConvertedDate($listingDateFormat);
?>
<div class="col-left sidebar">
    <div class="user-profile-image">
            <img class="profilephoto" src="<?php echo $getCustomerProfileImage; ?>">             <div class="view-edit-profile">
                  <h4><?php echo $getCusotmerData->getFirstname().' '.$getCusotmerData->getLastname(); ?></h4>
                  <a  target="_blank" href="#"><p class="view_profile_btn_dashboard"><span><?php echo __('View Profile'); ?></span></p></a>
                  <a  href="<?php echo $this->getEditProfileUrl(); ?>"><p class="verify_profile_no view_profile_btn_dashboard"><span><?php echo __('Edit Profile'); ?></span></p></a>
              </div>
  </div>

<div class="content-block">
    <div class="verify" style="position: relative;"><h2 class="account-heading"><?php echo __('Verified Info'); ?></h2>
      </div>
      <div class="account-heading-contents">
          <ul class="verify-info">
              <li><span class="verify-label"><?php echo __('Email ID'); ?></span><span><?php echo $getCusotmerData->getEmail();?></span><?php if($getCusotmerData->getEmail()){?><i class="sprite verifyed-icon"></i><?php } else {?><i class="sprite not-verifyed-icon"></i><?php }?></li>
              <li><span class="verify-label"><?php echo __('Phone Number'); ?></span><span><?php echo $profileData->getPhone();?></span><?php if($profileData->getPhone()){?><i class="sprite verifyed-icon"></i><?php } else {?><i class="sprite not-verifyed-icon"></i><?php }?></li>
              <li><span class="verify-label"><?php echo __('Bank Details'); ?></span><span><?php echo $profileData->getBankdetails();?></span><?php if($profileData->getBankdetails()){?><i class="sprite verifyed-icon"></i><?php } else {?><i class="sprite not-verifyed-icon"></i><?php }?></li>
              <li><span class="verify-label"><?php echo __('Date Of Birth'); ?></span><span><?php echo date($convertedDateFormat, strtotime($profileData->getDob()));?></span><?php if($profileData->getDob()){?><i class="sprite verifyed-icon"></i><?php } else {?><i class="sprite not-verifyed-icon"></i><?php }?></li>
          </ul>
      </div>
</div>
<div class="content-block sidebar-button">
    <div class="verify" style="position: relative;"><h2 class="account-heading" id = "sidebar-button"><?php echo __('Quick Links'); ?></h2>
        <i class="airhotel-sprite external-link dashnotify" title="Quick Links"></i>
    </div>
    <div class="account-heading-contents sidebar-menu" id = "sidebar-menu">
        <ul class="">
            <li><a href="<?php echo $this->getTripUrl()?>"><?php echo __('Upcoming Trips'); ?></a></li>
            <li><a href="<?php echo $this->getNewsletterUrl(); ?>"><?php echo __('Newsletter Subscription'); ?></a></li>
            <li><a href="<?php echo $this->getAddressbookUrl(); ?>"><?php echo __('Address Book'); ?></a></li>
          </ul>
      </div>
</div>
</div>

<script type="text/javascript">
   require(["jquery","jquery/ui",], function($){
$(document).ready(function(){
    $("#sidebar-button").click(function(){
        $("#sidebar-menu").toggle();
    });
});
});
</script>