<?php
/**
 * Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Airhotels
* @version     1.0.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/

?>
<?php 
$routeName = $this->helper('Apptha\Airhotels\Helper\General')->getRouteName();
?>
<div class="content-block">
    <div class="verify" style="position: relative;"><h2 class="account-heading"><?php echo __('Quick Links'); ?></h2>
        <i class="airhotel-sprite external-link dashnotify" title="Quick Links"></i>
    </div>
    <div class="account-heading-contents">
        <ul>
            <li><a href="<?php echo $this->getTripUrl()?>"><?php echo __('Upcoming Trips'); ?></a></li>
            <li><a href="<?php echo $this->getNewsletterUrl(); ?>" <?php if ($routeName =='newsletter'){?> class="selected" <?php }?>><?php echo __('Newsletter Subscription'); ?></a></li>
            <li><a href="<?php echo $this->getAddressbookUrl(); ?>" <?php if ($routeName =='customer'){?> class="selected" <?php }?>><?php echo __('Address Book'); ?></a></li>
          </ul>
      </div>
</div>
