<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Airhotels
 * @version     1.0.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$currentCustomerData=$this->getCustomerData();
$hostVerificationStatus = $block->getHostVerified ()->getHostTags();
?>
<div class="verification-block">
        <div class="verify-id clearfix">
            <div class="verify-description">
                <h2 class="account-heading">
                    <?php echo __('Verify Your ID'); ?>
                </h2>
                <p>
                    <?php echo __("Getting your Verified ID is the easiest way to help build trust in the Airhotels community.  We'll verify you by matching information from an online account to an official ID."); ?>  </p>
                <p>
                    <?php echo __("Or, you can choose to only add the verifications you want below."); ?></p>
            </div>
            <div class="verify-description text-center">
                <div class="verify-btn">
                  <i class="trust airhotel-sprite"></i>
                  <a href="<?php echo $this->getAccountVerificationUrl(); ?>" class="import_button">
                  <?php if($hostVerificationStatus == 1) {
                      echo __("Update Verification"); 
                      } else {
                          echo __("Verify Me"); 
                      } ?>
                  </a>
                </div>
            </div>
        </div>
        <div class="current-verification">
          <h3>
            <?php echo __('Your Current Verifications'); ?>
          </h3>
          <div class="panel-body">
              <ul>
                <li>
                  <h4><?php echo __('Email Address'); ?></h4>
                  <p>
                     <?php echo __('You have confirmed your email:'); ?> <b><?php echo $currentCustomerData->getCustomer()->getEmail(); ?></b>. <?php echo __('A confirmed email is important to allow us to securely communicate with you.'); ?>
                  </p>
                </li>                
              </ul>
          </div>
        </div>        
</div>