<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer')?>
    <?php if ($_totals):?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
                <?php else:?>
                            <?php 
$orderId = $this->getRequest()->getParam('order_id');
$getOrderInfo = $this->helper('\Apptha\Airhotels\Helper\Order')->getOrderInformation($orderId,'')->getData();
if(!empty($getOrderInfo[0]['service_fee']) && $_code == 'subtotal'){
     $currencySymbol = $this->helper('\Apptha\Airhotels\Helper\Order')->getCurrencySymbol();
?>
<tr class="col-<?php /* @escapeNotVerified */ echo $_code?>">
<td><strong><?php echo _('Processing Fee');?></strong></td>
<td><strong><?php echo $currencySymbol.$getOrderInfo[0]['service_fee'];?></strong></td>
</tr>
<?php } ?>
                <tr class="col-<?php /* @escapeNotVerified */ echo $_code?>">
                    <td <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> class="label">
                        <strong><?php echo $block->escapeHtml($_total->getLabel()); ?></strong>
                    </td>
                    <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?>>
                        <strong><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif?>
            <?php endforeach?>
        </tfoot>
    <?php endif?>
    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals):?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
                <?php else:?>
                    <tr class="col-<?php /* @escapeNotVerified */ echo $_code?>">
                        <td <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> class="label">
                            <?php if ($_total->getStrong()):?>
                            <strong><?php echo $block->escapeHtml($_total->getLabel()); ?></strong>
                            <?php else:?>
                            <?php echo $block->escapeHtml($_total->getLabel()); ?>
                            <?php endif?>
                        </td>

                        <?php if ($_total->getStrong()):?>
                            <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?>>
                                <strong><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else:?>
                            <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?>>
                                <span><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif?>
                    </tr>
                <?php endif?>
            <?php endforeach?>
        </tbody>
    <?php endif?>
</table>