<?php
/**
* Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Airhotels
* @version     1.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/

?>
<form action="" method="post" id="form-validate" class="form send confirmation" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <p class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email below and we will send you the confirmation link.') ?></p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action send primary"><span><?php /* @escapeNotVerified */ echo __('Send confirmation link') ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?php /* @escapeNotVerified */ echo $this->getUrl('customer/account/login'); ?>" class="action back"><span><?php /* @escapeNotVerified */ echo __('Back to Sign In') ?></span></a>
        </div>
    </div>
</form>
