<?php
/**
* Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Airhotels
* @version     1.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/
?>
<?php
$orderId = $this->getRequest()->getParam('order_id');
$getOrderInfo = $this->helper('\Apptha\Airhotels\Helper\Order')->getOrderInformation($orderId,'')->getData();
$customerData = $this->helper('\Apptha\Airhotels\Helper\Data')->getCustomerData();
$customerDataId = $customerData->getCustomerId();
$customerId = $getOrderInfo[0]['customer_id'] ;
if($customerDataId === $customerId){
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <?php
    if($_code!= 'subtotal' && $_code!= 'base_grandtotal' && !empty($getOrderInfo[0]['service_fee'])){
        $currencySymbol=  $this->helper('\Apptha\Airhotels\Helper\Order')->getOrderCurrencySymbol($block->getOrder()->getOrderCurrencyCode());
?>
<tr class="processing_fee">
<th colspan="6"><?php echo __('Processing Fee');?></th>
<td><?php echo $currencySymbol.$getOrderInfo[0]['service_fee'];?></td>
</tr>
<?php
}?>
    <tr class="<?php echo $_code?>">
        <td scope="row" colspan="6">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </td>
        <td <?php echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml($_total->getLabel());?>">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php echo $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
<?php }?>